/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      boxShadow: {
        menu: "0px 1px 2px 0px hsla(0, 0%, 0%, 0.25)",
      },
      colors: {
        text: "hsla(0, 0%, 9%, 1)",
        primary: "hsla(263, 70%, 50%, 1)",
        secondary: "hsla(0, 0%, 90%, 1)",
        muted: "hsla(0, 0%, 96%, 1)",
        "primary-hover": "hsla(263, 70%, 60%, 1)",
        "secondary-hover": "hsla(0, 0%, 80%, 1)",
        "outline-hover": "hsla(0, 0%, 90%, 1)",
        "primary-active": "hsla(263, 69%, 42%, 1)",
        "secondary-active": "hsla(0, 0%, 64%, 1)",
        "outline-active": "hsla(0, 0%, 96%, 1)",
        "primary-foreground": "hsla(0, 0%, 100%, 1)",
        "secondary-foreground": "hsla(0, 0%, 15%, 1)",
        "muted-foreground": "hsla(0, 0%, 32%, 1)",
        border: "hsla(0, 0%, 83%, 1)",
        ring: "hsla(0, 0%, 83%, 1)",
        background: "hsla(0, 0%, 100%, 1)",
        color1: "#E1E7EF",
        color2: "#FEC8C8",
        color3: "#FED6A9",
        color4: "#FEF08B",
        color5: "#D9F99F",
        color6: "#BEDBFE",
        color7: "#FBD0E8",
        color8: "#DED7FE",
        danger: "hsla(0, 86%, 97%, 1)",
        "danger-border": "hsla(0, 72%, 51%, 1)",
        "danger-hover": "hsla(0, 72%, 61%, 1)",
        "danger-active": "hsla(0, 72%, 41%, 1)",
        "danger-foreground": "hsla(0, 75%, 15%, 1)",
      },
      fontFamily: {
        welcome: ["Familjen Grotesk Variable", "Inter"],
      },
    },
  },
  plugins: [],
};
